version: '3.6'

services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    restart: unless-stopped
    networks:
      - ptgh
    ports:
      - "5432:5432"
    env_file:
      - .env
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]

networks:
  ptgh:
    name: ptgh